---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQxMjM=
  mysql-database: d29yZHByZXNz
  mysql-user: d29yZHByZXNz
  mysql-password: d29yZHByZXNzMTIz
